// Package clientgen generates TypeScript client code from a CSAR config.
package clientgen

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/ledatu/csar/internal/config"
)

// Options configures the client generation.
type Options struct {
	// BaseURL is the base URL for the generated client.
	BaseURL string

	// ClassName is the TypeScript class name. Default: "CsarClient".
	ClassName string

	// UseAxios generates Axios-based code; otherwise uses Fetch.
	UseAxios bool
}

// Generate produces TypeScript client code from a CSAR config.
func Generate(cfg *config.Config, opts Options) (string, error) {
	if opts.ClassName == "" {
		opts.ClassName = "CsarClient"
	}
	if opts.BaseURL == "" {
		// Try to derive from listen_addr
		if cfg.ListenAddr != "" {
			opts.BaseURL = "http://" + cfg.ListenAddr
		} else {
			opts.BaseURL = "http://localhost:8080"
		}
	}

	var b strings.Builder

	// Header
	fmt.Fprintf(&b, `/**
 * CSAR API Client — auto-generated by csar-helper client-gen
 * Generated at: %s
 *
 * This client is preconfigured with rate limit awareness and
 * X-CSAR-Wait-MS header support for the CSAR API gateway.
 */

`, time.Now().Format(time.RFC3339))

	if opts.UseAxios {
		b.WriteString("import axios, { AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';\n\n")
	}

	// Types
	b.WriteString(`// ─── Types ──────────────────────────────────────────────────────────────────

export interface CsarClientConfig {
  baseURL: string;
  /** Maximum time (ms) the gateway should hold a throttled request. */
  defaultMaxWait?: number;
  /** Default headers for all requests. */
  headers?: Record<string, string>;
  /** Request timeout in ms. */
  timeout?: number;
}

export interface CsarResponse<T = unknown> {
  data: T;
  status: number;
  headers: Record<string, string>;
  /** Server-side wait time in ms (from X-CSAR-Wait-MS header). */
  csarWaitMs?: number;
}

`)

	// Route type definitions
	b.WriteString("// ─── Route definitions ──────────────────────────────────────────────────────\n\n")

	var routes []routeEntry
	for path, methods := range cfg.Paths {
		for method := range methods {
			route := methods[method]
			routes = append(routes, routeEntry{path, method, route})
		}
	}
	sort.Slice(routes, func(i, j int) bool {
		if routes[i].path == routes[j].path {
			return routes[i].method < routes[j].method
		}
		return routes[i].path < routes[j].path
	})

	// Generate route info as typed constants
	b.WriteString("export const ROUTES = {\n")
	for i := range routes {
		r := &routes[i]
		safeName := routeToConstName(r.path, r.method)
		maxWait := 0
		if r.route.Traffic != nil && r.route.Traffic.MaxWait.Duration > 0 {
			maxWait = int(r.route.Traffic.MaxWait.Duration / time.Millisecond)
		}
		rps := 0.0
		if r.route.Traffic != nil {
			rps = r.route.Traffic.RPS
		}
		fmt.Fprintf(&b, "  %s: {\n", safeName)
		fmt.Fprintf(&b, "    path: '%s',\n", r.path)
		fmt.Fprintf(&b, "    method: '%s',\n", strings.ToUpper(r.method))
		if rps > 0 {
			fmt.Fprintf(&b, "    rps: %g,\n", rps)
		}
		if maxWait > 0 {
			fmt.Fprintf(&b, "    maxWaitMs: %d,\n", maxWait)
		}
		b.WriteString("  },\n")
	}
	b.WriteString("} as const;\n\n")

	// Generate client class
	if opts.UseAxios {
		generateAxiosClient(&b, opts, routes)
	} else {
		generateFetchClient(&b, opts, routes)
	}

	return b.String(), nil
}

func generateFetchClient(b *strings.Builder, opts Options, routes []routeEntry) {
	fmt.Fprintf(b, `// ─── Client ─────────────────────────────────────────────────────────────────

export class %s {
  private baseURL: string;
  private defaultMaxWait: number;
  private defaultHeaders: Record<string, string>;
  private timeout: number;

  constructor(config: CsarClientConfig) {
    this.baseURL = config.baseURL || '%s';
    this.defaultMaxWait = config.defaultMaxWait ?? 5000;
    this.defaultHeaders = config.headers ?? {};
    this.timeout = config.timeout ?? 30000;
  }

  private async request<T = unknown>(
    method: string,
    path: string,
    options?: {
      body?: unknown;
      headers?: Record<string, string>;
      maxWaitMs?: number;
      params?: Record<string, string>;
    },
  ): Promise<CsarResponse<T>> {
    const url = new URL(path, this.baseURL);
    if (options?.params) {
      for (const [k, v] of Object.entries(options.params)) {
        url.searchParams.set(k, v);
      }
    }

    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
      ...this.defaultHeaders,
      ...options?.headers,
    };

    // Set the X-CSAR-Wait-MS header so the gateway knows our patience budget.
    const maxWait = options?.maxWaitMs ?? this.defaultMaxWait;
    if (maxWait > 0) {
      headers['X-CSAR-Wait-MS'] = String(maxWait);
    }

    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), this.timeout);

    try {
      const resp = await fetch(url.toString(), {
        method,
        headers,
        body: options?.body ? JSON.stringify(options.body) : undefined,
        signal: controller.signal,
      });

      const csarWaitMs = resp.headers.get('X-CSAR-Wait-MS');
      const data = resp.headers.get('content-type')?.includes('application/json')
        ? await resp.json()
        : await resp.text();

      return {
        data: data as T,
        status: resp.status,
        headers: Object.fromEntries(resp.headers.entries()),
        csarWaitMs: csarWaitMs ? parseInt(csarWaitMs, 10) : undefined,
      };
    } finally {
      clearTimeout(timeoutId);
    }
  }

`, opts.ClassName, opts.BaseURL)

	// Generate methods for each route
	for i := range routes {
		r := &routes[i]
		methodName := routeToMethodName(r.path, r.method)
		hasBody := r.method == "post" || r.method == "put" || r.method == "patch"

		// Extract path params
		pathParams := extractPathParams(r.path)

		params := []string{}
		for _, p := range pathParams {
			params = append(params, fmt.Sprintf("%s: string", p))
		}
		if hasBody {
			params = append(params, "body?: unknown")
		}
		params = append(params, "options?: { headers?: Record<string, string>; maxWaitMs?: number; params?: Record<string, string> }")

		fmt.Fprintf(b, "  /** %s %s */\n", strings.ToUpper(r.method), r.path)
		fmt.Fprintf(b, "  async %s(%s): Promise<CsarResponse> {\n", methodName, strings.Join(params, ", "))

		// Build path with param substitution
		pathExpr := r.path
		for _, p := range pathParams {
			pathExpr = strings.ReplaceAll(pathExpr, "{"+p+"}", "${"+p+"}")
			// Also handle {name:regex} form
			idx := strings.Index(pathExpr, "{"+p+":")
			if idx >= 0 {
				end := strings.Index(pathExpr[idx:], "}")
				if end > 0 {
					pathExpr = pathExpr[:idx] + "${" + p + "}" + pathExpr[idx+end+1:]
				}
			}
		}

		if len(pathParams) > 0 {
			if hasBody {
				fmt.Fprintf(b, "    return this.request('%s', `%s`, { body, ...options });\n",
					strings.ToUpper(r.method), pathExpr)
			} else {
				fmt.Fprintf(b, "    return this.request('%s', `%s`, options);\n",
					strings.ToUpper(r.method), pathExpr)
			}
		} else {
			if hasBody {
				fmt.Fprintf(b, "    return this.request('%s', '%s', { body, ...options });\n",
					strings.ToUpper(r.method), r.path)
			} else {
				fmt.Fprintf(b, "    return this.request('%s', '%s', options);\n",
					strings.ToUpper(r.method), r.path)
			}
		}
		b.WriteString("  }\n\n")
	}

	b.WriteString("}\n")
}

func generateAxiosClient(b *strings.Builder, opts Options, routes []routeEntry) {
	fmt.Fprintf(b, `// ─── Client ─────────────────────────────────────────────────────────────────

export class %s {
  private client: AxiosInstance;
  private defaultMaxWait: number;

  constructor(config: CsarClientConfig) {
    this.defaultMaxWait = config.defaultMaxWait ?? 5000;
    this.client = axios.create({
      baseURL: config.baseURL || '%s',
      timeout: config.timeout ?? 30000,
      headers: {
        'Content-Type': 'application/json',
        ...config.headers,
      },
    });

    // Interceptor: inject X-CSAR-Wait-MS header
    this.client.interceptors.request.use((cfg) => {
      if (!cfg.headers['X-CSAR-Wait-MS']) {
        cfg.headers['X-CSAR-Wait-MS'] = String(this.defaultMaxWait);
      }
      return cfg;
    });
  }

  private async request<T = unknown>(
    method: string,
    path: string,
    config?: AxiosRequestConfig & { maxWaitMs?: number },
  ): Promise<CsarResponse<T>> {
    if (config?.maxWaitMs) {
      config.headers = { ...config.headers, 'X-CSAR-Wait-MS': String(config.maxWaitMs) };
    }

    const resp: AxiosResponse<T> = await this.client.request({
      method,
      url: path,
      ...config,
    });

    return {
      data: resp.data,
      status: resp.status,
      headers: resp.headers as Record<string, string>,
      csarWaitMs: resp.headers['x-csar-wait-ms']
        ? parseInt(resp.headers['x-csar-wait-ms'], 10)
        : undefined,
    };
  }

`, opts.ClassName, opts.BaseURL)

	// Generate methods
	for i := range routes {
		r := &routes[i]
		methodName := routeToMethodName(r.path, r.method)
		hasBody := r.method == "post" || r.method == "put" || r.method == "patch"

		pathParams := extractPathParams(r.path)
		params := []string{}
		for _, p := range pathParams {
			params = append(params, fmt.Sprintf("%s: string", p))
		}
		if hasBody {
			params = append(params, "data?: unknown")
		}
		params = append(params, "config?: AxiosRequestConfig & { maxWaitMs?: number }")

		fmt.Fprintf(b, "  /** %s %s */\n", strings.ToUpper(r.method), r.path)
		fmt.Fprintf(b, "  async %s(%s): Promise<CsarResponse> {\n", methodName, strings.Join(params, ", "))

		pathExpr := r.path
		for _, p := range pathParams {
			pathExpr = strings.ReplaceAll(pathExpr, "{"+p+"}", "${"+p+"}")
		}

		if hasBody {
			fmt.Fprintf(b, "    return this.request('%s', `%s`, { data, ...config });\n",
				strings.ToUpper(r.method), pathExpr)
		} else {
			fmt.Fprintf(b, "    return this.request('%s', `%s`, config);\n",
				strings.ToUpper(r.method), pathExpr)
		}
		b.WriteString("  }\n\n")
	}

	b.WriteString("}\n")
}

// ─── Helpers ───────────────────────────────────────────────────────────────────

func routeToConstName(path, method string) string {
	parts := strings.Split(strings.Trim(path, "/"), "/")
	var clean []string
	for _, p := range parts {
		p = strings.TrimLeft(p, "{")
		p = strings.TrimRight(p, "}")
		if idx := strings.Index(p, ":"); idx > 0 {
			p = p[:idx]
		}
		if p != "" {
			clean = append(clean, strings.ToUpper(p))
		}
	}
	return strings.ToUpper(method) + "_" + strings.Join(clean, "_")
}

func routeToMethodName(path, method string) string {
	parts := strings.Split(strings.Trim(path, "/"), "/")
	var clean []string
	for _, p := range parts {
		p = strings.TrimLeft(p, "{")
		p = strings.TrimRight(p, "}")
		if idx := strings.Index(p, ":"); idx > 0 {
			p = p[:idx]
		}
		if p != "" {
			clean = append(clean, capitalize(p))
		}
	}
	return strings.ToLower(method) + strings.Join(clean, "")
}

func extractPathParams(path string) []string {
	var params []string
	parts := strings.Split(path, "/")
	for _, p := range parts {
		if strings.HasPrefix(p, "{") && strings.HasSuffix(p, "}") {
			name := p[1 : len(p)-1]
			if idx := strings.Index(name, ":"); idx > 0 {
				name = name[:idx]
			}
			params = append(params, name)
		}
	}
	return params
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

type routeEntry struct {
	path   string
	method string
	route  config.RouteConfig
}
