package tui

import (
	"fmt"
	"strings"
)

// renderEnvExample generates the .env.example content from wizard results.
func renderEnvExample(r *GenerateResult) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("# CSAR Environment Variables — %s\n", r.ProjectName))
	b.WriteString(fmt.Sprintf("# Profile: %s\n", r.Profile))
	b.WriteString("# Generated by: csar-helper generate\n")
	b.WriteString("# Copy to .env and fill in real values.\n\n")

	// TLS
	if r.EnableTLS {
		b.WriteString("# TLS certificates\n")
		b.WriteString(fmt.Sprintf("CSAR_TLS_CERT_FILE=%s\n", r.TLSCert))
		b.WriteString(fmt.Sprintf("CSAR_TLS_KEY_FILE=%s\n", r.TLSKey))
		b.WriteString("\n")
	}

	// KMS
	b.WriteString("# KMS provider\n")
	b.WriteString(fmt.Sprintf("CSAR_KMS_PROVIDER=%s\n", r.KMSProvider))
	if r.KMSProvider == "local" {
		b.WriteString("CSAR_KMS_LOCAL_KEYS=dev-key=dev-passphrase\n")
	} else {
		b.WriteString("CSAR_KMS_KEY_ID=your-kms-key-id\n")
	}
	b.WriteString("\n")

	// Coordinator
	if r.EnableCoordinator {
		b.WriteString("# Coordinator connection (gRPC)\n")
		b.WriteString(fmt.Sprintf("CSAR_COORDINATOR_ADDRESS=%s\n", r.CoordinatorAddress))
		isProd := r.Profile == "prod-single" || r.Profile == "prod-distributed"
		if isProd {
			b.WriteString("CSAR_COORDINATOR_CA_FILE=/etc/csar/tls/coordinator-ca.pem\n")
			b.WriteString("CSAR_COORDINATOR_CERT_FILE=/etc/csar/tls/router-client-cert.pem\n")
			b.WriteString("CSAR_COORDINATOR_KEY_FILE=/etc/csar/tls/router-client-key.pem\n")
		}
		b.WriteString("\n")
	}

	// Redis
	if r.RateLimitBackend == "redis" {
		b.WriteString("# Redis\n")
		b.WriteString(fmt.Sprintf("REDIS_ADDRESS=%s\n", r.RedisAddress))
		if r.RedisPassword != "" {
			b.WriteString(fmt.Sprintf("REDIS_PASSWORD=%s\n", r.RedisPassword))
		} else {
			b.WriteString("REDIS_PASSWORD=\n")
		}
		b.WriteString("\n")
	}

	// Upstream
	b.WriteString("# Upstream targets\n")
	if len(r.Routes) > 0 {
		b.WriteString(fmt.Sprintf("CSAR_UPSTREAM_URL=%s\n", r.Routes[0].TargetURL))
	} else {
		b.WriteString("CSAR_UPSTREAM_URL=http://localhost:3000\n")
	}
	b.WriteString("\n")

	// Token store
	if r.IncludePostgres {
		b.WriteString("# Token store DSN (for coordinator)\n")
		b.WriteString(fmt.Sprintf("CSAR_TOKEN_STORE_DSN=postgres://csar:%s@postgres:5432/csar?sslmode=disable\n", r.PostgresPassword))
		b.WriteString(fmt.Sprintf("POSTGRES_PASSWORD=%s\n", r.PostgresPassword))
		b.WriteString("\n")
	}

	// Metrics
	b.WriteString("# Metrics\n")
	b.WriteString("CSAR_METRICS_ADDR=:9100\n")

	return b.String()
}
