package tui

import (
	"fmt"
	"path/filepath"
	"strings"
)

// renderDockerCompose generates the docker-compose.yaml content from wizard results.
func renderDockerCompose(r *GenerateResult) string {
	var b strings.Builder

	// Calculate build context relative to the output directory.
	// If output is a subdirectory, build context should point to the repo root.
	buildContext := "."
	if r.OutputDir != "." && r.OutputDir != "" {
		// Count depth of output dir to compute relative path back to repo root
		abs, err := filepath.Abs(r.OutputDir)
		if err == nil {
			cwd, _ := filepath.Abs(".")
			rel, err := filepath.Rel(abs, cwd)
			if err == nil && rel != "." {
				buildContext = rel
			}
		}
	}

	b.WriteString(fmt.Sprintf("# Docker Compose — %s\n", r.ProjectName))
	b.WriteString("# Generated by: csar-helper generate\n")
	b.WriteString("#\n")
	b.WriteString("# Usage:\n")
	b.WriteString("#   cp .env.example .env   # fill in real values\n")
	b.WriteString("#   docker compose up -d\n\n")

	b.WriteString("services:\n")

	// ─── Coordinator ────────────────────────────────────────────────────────────
	if r.IncludeCoordinator {
		coordPort := portOrDefault(r.CoordinatorPort, "9090")
		b.WriteString("  coordinator:\n")
		b.WriteString("    image: csar-coordinator:latest\n")
		b.WriteString("    container_name: csar-coordinator\n")
		b.WriteString("    restart: unless-stopped\n")
		b.WriteString("    ports:\n")
		b.WriteString(fmt.Sprintf("      - \"%s:9090\"\n", coordPort))
		b.WriteString("    environment:\n")
		b.WriteString("      - CSAR_TOKEN_STORE_DSN=${CSAR_TOKEN_STORE_DSN}\n")
		if r.EnableTLS {
			b.WriteString("    volumes:\n")
			b.WriteString("      - ./tls:/etc/csar/tls:ro\n")
			b.WriteString("    command: >\n")
			b.WriteString("      -listen :9090\n")
			b.WriteString("      -token-store postgres\n")
			b.WriteString("      -token-store-dsn ${CSAR_TOKEN_STORE_DSN}\n")
			b.WriteString("      -tls-cert /etc/csar/tls/coordinator-cert.pem\n")
			b.WriteString("      -tls-key /etc/csar/tls/coordinator-key.pem\n")
			b.WriteString("      -tls-ca /etc/csar/tls/ca.pem\n")
		} else {
			b.WriteString("    command: >\n")
			b.WriteString("      -listen :9090\n")
			b.WriteString("      -token-store postgres\n")
			b.WriteString("      -token-store-dsn ${CSAR_TOKEN_STORE_DSN}\n")
		}
		if r.IncludePostgres {
			b.WriteString("    depends_on:\n")
			b.WriteString("      postgres:\n")
			b.WriteString("        condition: service_healthy\n")
		}
		b.WriteString("    networks:\n")
		b.WriteString("      - csar\n")
		b.WriteString("\n")
	}

	// ─── Router ─────────────────────────────────────────────────────────────────
	routerPort := portOrDefault(r.RouterPort, "8080")
	metricsPort := portOrDefault(r.MetricsPort, "9100")

	b.WriteString("  router:\n")
	b.WriteString("    image: csar:latest\n")
	b.WriteString("    container_name: csar-router\n")
	b.WriteString("    restart: unless-stopped\n")
	b.WriteString("    ports:\n")
	b.WriteString(fmt.Sprintf("      - \"%s:8080\"\n", routerPort))
	b.WriteString(fmt.Sprintf("      - \"%s:9100\"\n", metricsPort))

	// depends_on
	var deps []string
	if r.IncludeCoordinator {
		deps = append(deps, "coordinator")
	}
	if r.IncludeRedis {
		deps = append(deps, "redis")
	}
	if r.IncludeDBInit {
		deps = append(deps, "db-init")
	}
	if len(deps) > 0 {
		b.WriteString("    depends_on:\n")
		for _, dep := range deps {
			b.WriteString(fmt.Sprintf("      %s:\n", dep))
			b.WriteString("        condition: service_completed_successfully\n")
		}
	}

	b.WriteString("    volumes:\n")
	b.WriteString("      - ./config.yaml:/etc/csar/config.yaml:ro\n")
	if r.EnableTLS {
		b.WriteString("      - ./tls:/etc/csar/tls:ro\n")
	}
	b.WriteString("    environment:\n")
	b.WriteString("      - CSAR_KMS_PROVIDER=${CSAR_KMS_PROVIDER:-local}\n")
	if r.KMSProvider == "local" {
		b.WriteString("      - CSAR_KMS_LOCAL_KEYS=${CSAR_KMS_LOCAL_KEYS:-dev-key=dev-passphrase}\n")
	}
	// Yandex KMS environment variables
	if r.KMSProvider == "yandexapi" {
		b.WriteString("      - YANDEX_IAM_TOKEN=${YANDEX_IAM_TOKEN}\n")
	}
	// Coordinator TLS environment variables for the router
	if r.EnableCoordinator && r.EnableTLS {
		b.WriteString("      - CSAR_COORDINATOR_CA_FILE=/etc/csar/tls/ca.pem\n")
		b.WriteString("      - CSAR_COORDINATOR_CERT_FILE=/etc/csar/tls/client-cert.pem\n")
		b.WriteString("      - CSAR_COORDINATOR_KEY_FILE=/etc/csar/tls/client-key.pem\n")
	}
	b.WriteString("    command: >\n")
	b.WriteString("      -config /etc/csar/config.yaml\n")
	b.WriteString("      -kms-provider ${CSAR_KMS_PROVIDER:-local}\n")
	b.WriteString("      -metrics-addr :9100\n")

	// Self-healing healthcheck: use HTTPS when TLS is enabled
	b.WriteString("    healthcheck:\n")
	if r.EnableTLS {
		b.WriteString("      test: [\"CMD\", \"wget\", \"--no-check-certificate\", \"-q\", \"--spider\", \"https://localhost:8080/health\"]\n")
	} else {
		b.WriteString("      test: [\"CMD\", \"wget\", \"-q\", \"--spider\", \"http://localhost:8080/health\"]\n")
	}
	b.WriteString("      interval: 10s\n")
	b.WriteString("      timeout: 3s\n")
	b.WriteString("      retries: 3\n")
	b.WriteString("    networks:\n")
	b.WriteString("      - csar\n")
	b.WriteString("\n")

	// ─── DB Init ────────────────────────────────────────────────────────────────
	if r.IncludeDBInit || (r.IncludePostgres && r.IncludeCoordinator) {
		b.WriteString("  db-init:\n")
		b.WriteString(fmt.Sprintf("    build:\n      context: %s\n      dockerfile: Dockerfile\n", buildContext))
		b.WriteString("    container_name: csar-db-init\n")
		b.WriteString("    environment:\n")
		b.WriteString("      - CSAR_TOKEN_STORE_DSN=${CSAR_TOKEN_STORE_DSN}\n")
		b.WriteString("    command: [\"csar-helper\", \"db\", \"init\", \"--dsn\", \"${CSAR_TOKEN_STORE_DSN}\"]\n")
		if r.IncludePostgres {
			b.WriteString("    depends_on:\n")
			b.WriteString("      postgres:\n")
			b.WriteString("        condition: service_healthy\n")
		}
		b.WriteString("    networks:\n")
		b.WriteString("      - csar\n")
		b.WriteString("\n")
	}

	// ─── Redis ──────────────────────────────────────────────────────────────────
	if r.IncludeRedis {
		b.WriteString("  redis:\n")
		b.WriteString("    image: redis:7-alpine\n")
		b.WriteString("    container_name: csar-redis\n")
		b.WriteString("    restart: unless-stopped\n")
		b.WriteString("    ports:\n")
		b.WriteString("      - \"6379:6379\"\n")
		if r.RedisPassword != "" {
			b.WriteString(fmt.Sprintf("    command: redis-server --requirepass ${REDIS_PASSWORD:-%s} --maxmemory 128mb --maxmemory-policy allkeys-lru\n", r.RedisPassword))
		} else {
			b.WriteString("    command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru\n")
		}
		b.WriteString("    healthcheck:\n")
		if r.RedisPassword != "" {
			b.WriteString("      test: [\"CMD\", \"redis-cli\", \"-a\", \"${REDIS_PASSWORD}\", \"ping\"]\n")
		} else {
			b.WriteString("      test: [\"CMD\", \"redis-cli\", \"ping\"]\n")
		}
		b.WriteString("      interval: 10s\n")
		b.WriteString("      timeout: 3s\n")
		b.WriteString("      retries: 3\n")
		b.WriteString("    networks:\n")
		b.WriteString("      - csar\n")
		b.WriteString("\n")
	}

	// ─── PostgreSQL ─────────────────────────────────────────────────────────────
	if r.IncludePostgres {
		pgPass := r.PostgresPassword
		if pgPass == "" {
			pgPass = "csar_dev"
		}
		b.WriteString("  postgres:\n")
		b.WriteString("    image: postgres:16-alpine\n")
		b.WriteString("    container_name: csar-postgres\n")
		b.WriteString("    restart: unless-stopped\n")
		b.WriteString("    environment:\n")
		b.WriteString("      POSTGRES_DB: csar\n")
		b.WriteString("      POSTGRES_USER: csar\n")
		b.WriteString(fmt.Sprintf("      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-%s}\n", pgPass))
		b.WriteString("    ports:\n")
		b.WriteString("      - \"5432:5432\"\n")
		b.WriteString("    volumes:\n")
		b.WriteString("      - pgdata:/var/lib/postgresql/data\n")
		b.WriteString("    healthcheck:\n")
		b.WriteString("      test: [\"CMD-SHELL\", \"pg_isready -U csar\"]\n")
		b.WriteString("      interval: 10s\n")
		b.WriteString("      timeout: 3s\n")
		b.WriteString("      retries: 5\n")
		b.WriteString("    networks:\n")
		b.WriteString("      - csar\n")
		b.WriteString("\n")
	}

	// ─── Volumes ────────────────────────────────────────────────────────────────
	if r.IncludePostgres {
		b.WriteString("volumes:\n")
		b.WriteString("  pgdata:\n\n")
	}

	// ─── Networks ───────────────────────────────────────────────────────────────
	b.WriteString("networks:\n")
	b.WriteString("  csar:\n")
	b.WriteString("    driver: bridge\n")

	return b.String()
}
