package tui

import (
	"fmt"
	"strings"
)

// renderEnvExample generates the .env.example content from wizard results.
func renderEnvExample(r *GenerateResult) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("# CSAR Environment Variables — %s\n", r.ProjectName))
	b.WriteString(fmt.Sprintf("# Profile: %s\n", r.Profile))
	b.WriteString("# Generated by: csar-helper generate\n")
	b.WriteString("# Copy to .env and fill in real values.\n\n")

	// TLS
	if r.EnableTLS {
		b.WriteString("# TLS certificates\n")
		b.WriteString(fmt.Sprintf("CSAR_TLS_CERT_FILE=%s\n", r.TLSCert))
		b.WriteString(fmt.Sprintf("CSAR_TLS_KEY_FILE=%s\n", r.TLSKey))
		if r.TLSCA != "" {
			b.WriteString(fmt.Sprintf("CSAR_TLS_CA_FILE=%s\n", r.TLSCA))
		}
		b.WriteString("\n")
	}

	// KMS
	b.WriteString("# KMS provider\n")
	b.WriteString(fmt.Sprintf("CSAR_KMS_PROVIDER=%s\n", r.KMSProvider))
	if r.KMSProvider == "local" {
		b.WriteString("CSAR_KMS_LOCAL_KEYS=dev-key=dev-passphrase\n")
	} else if r.KMSProvider == "yandexapi" {
		if r.YandexKMSKeyID != "" {
			b.WriteString(fmt.Sprintf("CSAR_KMS_KEY_ID=%s\n", r.YandexKMSKeyID))
		} else {
			b.WriteString("CSAR_KMS_KEY_ID=<your-kms-key-id>\n")
		}
		b.WriteString("\n")
		b.WriteString("# Yandex Cloud KMS — IAM token for authentication\n")
		b.WriteString("# Generate with: yc iam create-token\n")
		// Never persist secrets — always use a placeholder.
		b.WriteString("YANDEX_IAM_TOKEN=<your-yandex-iam-token>\n")
	} else {
		b.WriteString("CSAR_KMS_KEY_ID=your-kms-key-id\n")
	}
	b.WriteString("\n")

	// Coordinator
	if r.EnableCoordinator {
		b.WriteString("# Coordinator connection (gRPC)\n")
		b.WriteString(fmt.Sprintf("CSAR_COORDINATOR_ADDRESS=%s\n", r.CoordinatorAddress))
		if r.EnableTLS {
			b.WriteString(fmt.Sprintf("CSAR_COORDINATOR_CA_FILE=%s\n", r.CoordinatorCACert))
			b.WriteString(fmt.Sprintf("CSAR_COORDINATOR_CERT_FILE=%s\n", r.CoordinatorCertFile))
			b.WriteString(fmt.Sprintf("CSAR_COORDINATOR_KEY_FILE=%s\n", r.CoordinatorKeyFile))
		}
		b.WriteString("\n")
	}

	// Redis
	if r.RateLimitBackend == "redis" {
		b.WriteString("# Redis\n")
		b.WriteString(fmt.Sprintf("REDIS_ADDRESS=%s\n", r.RedisAddress))
		// Never persist secrets — always use a placeholder.
		b.WriteString("REDIS_PASSWORD=<your-redis-password>\n")
		b.WriteString("\n")
	}

	// Upstream
	b.WriteString("# Upstream targets\n")
	if len(r.Routes) > 0 {
		b.WriteString(fmt.Sprintf("CSAR_UPSTREAM_URL=%s\n", r.Routes[0].TargetURL))
	} else {
		b.WriteString("CSAR_UPSTREAM_URL=http://localhost:3000\n")
	}
	b.WriteString("\n")

	// Token store
	if r.IncludePostgres {
		b.WriteString("# Token store DSN (for coordinator)\n")
		// Never persist secrets — use placeholders.
		b.WriteString("CSAR_TOKEN_STORE_DSN=postgres://csar:<password>@postgres:5432/csar?sslmode=disable\n")
		b.WriteString("POSTGRES_PASSWORD=<your-postgres-password>\n")
		b.WriteString("\n")
	}

	// Metrics
	b.WriteString("# Metrics\n")
	b.WriteString("CSAR_METRICS_ADDR=:9100\n")

	return b.String()
}
