package tui

import (
	"fmt"
	"strings"
)

// renderConfigYAML generates the config.yaml content from wizard results.
func renderConfigYAML(r *GenerateResult) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("# CSAR Configuration — %s\n", r.ProjectName))
	b.WriteString(fmt.Sprintf("# Profile: %s\n", r.Profile))
	b.WriteString("# Generated by: csar-helper generate\n\n")

	b.WriteString(fmt.Sprintf("profile: %s\n\n", r.Profile))
	b.WriteString(fmt.Sprintf("listen_addr: %q\n\n", r.ListenAddr))

	// TLS
	if r.EnableTLS {
		b.WriteString("tls:\n")
		b.WriteString(fmt.Sprintf("  cert_file: %q\n", r.TLSCert))
		b.WriteString(fmt.Sprintf("  key_file: %q\n", r.TLSKey))
		b.WriteString(fmt.Sprintf("  min_version: %q\n", r.TLSMinVer))
		b.WriteString("  # Uncomment for mTLS:\n")
		b.WriteString("  # client_ca_file: \"/etc/csar/tls/client-ca.pem\"\n\n")
	}

	// Security policy
	isProd := r.Profile == "prod-single" || r.Profile == "prod-distributed"
	if isProd {
		b.WriteString("security_policy:\n")
		b.WriteString("  environment: \"prod\"\n")
		b.WriteString("  forbid_insecure_in_prod: true\n")
		b.WriteString("  redact_sensitive_logs: true\n")
		if r.Profile == "prod-distributed" {
			b.WriteString("  require_mtls_for_coordinator: true\n")
		}
		b.WriteString("\n")
	}

	// SSRF
	if r.EnableSSRF {
		b.WriteString("ssrf_protection:\n")
		b.WriteString("  block_private: true\n")
		b.WriteString("  block_loopback: true\n")
		b.WriteString("  block_link_local: true\n")
		b.WriteString("  block_metadata: true\n\n")
	}

	// KMS — with full Yandex configuration when applicable
	if r.KMSProvider != "" {
		b.WriteString("kms:\n")
		b.WriteString(fmt.Sprintf("  provider: %q\n", r.KMSProvider))

		if r.KMSProvider == "yandexapi" {
			// Yandex-specific block with auth_mode and token
			b.WriteString("  yandex:\n")
			authMode := r.YandexAuthMode
			if authMode == "" {
				authMode = "iam_token"
			}
			b.WriteString(fmt.Sprintf("    auth_mode: %q\n", authMode))
			if authMode == "iam_token" {
				// Never persist secrets into generated files — always use env var reference.
				// The actual token should be set via YANDEX_IAM_TOKEN env var or a secrets manager.
				b.WriteString("    iam_token: \"${YANDEX_IAM_TOKEN}\"\n")
			}
			if r.YandexKMSKeyID != "" {
				b.WriteString(fmt.Sprintf("  default_key_id: %q\n", r.YandexKMSKeyID))
			}
			b.WriteString("  cache:\n")
			b.WriteString("    enabled: true\n")
			b.WriteString("    ttl: \"60s\"\n")
			b.WriteString("    max_entries: 10000\n")
		} else if r.KMSProvider != "local" {
			b.WriteString("  cache:\n")
			b.WriteString("    enabled: true\n")
			b.WriteString("    ttl: \"60s\"\n")
			b.WriteString("    max_entries: 10000\n")
		} else {
			b.WriteString("  # Configure keys inline or via CLI flags:\n")
			b.WriteString("  # local_keys:\n")
			b.WriteString("  #   dev-key: \"dev-passphrase\"\n")
		}
		b.WriteString("\n")
	}

	// Security profiles — collect unique security configs from routes
	secProfiles := collectSecurityProfiles(r)
	if len(secProfiles) > 0 {
		b.WriteString("security_profiles:\n")
		for name, sec := range secProfiles {
			b.WriteString(fmt.Sprintf("  %s:\n", name))
			if sec.KMSKeyID != "" {
				b.WriteString(fmt.Sprintf("    kms_key_id: %q\n", sec.KMSKeyID))
			}
			b.WriteString(fmt.Sprintf("    token_ref: %q\n", sec.TokenRef))
			b.WriteString(fmt.Sprintf("    inject_header: %q\n", sec.InjectHeader))
			b.WriteString(fmt.Sprintf("    inject_format: %q\n", sec.InjectFormat))
		}
		b.WriteString("\n")
	}

	// Redis
	if r.RateLimitBackend == "redis" {
		addr := r.RedisAddress
		if addr == "" {
			addr = "redis:6379"
		}
		b.WriteString("redis:\n")
		b.WriteString(fmt.Sprintf("  address: %q\n", addr))
		// Never persist Redis password — use env var reference.
		b.WriteString("  password: \"${REDIS_PASSWORD}\"\n")
		b.WriteString("  key_prefix: \"csar:rl:\"\n\n")
	}

	// Coordinator
	b.WriteString("coordinator:\n")
	b.WriteString(fmt.Sprintf("  enabled: %t\n", r.EnableCoordinator))
	if r.EnableCoordinator {
		b.WriteString(fmt.Sprintf("  address: %q\n", r.CoordinatorAddress))
		if r.EnableTLS {
			b.WriteString(fmt.Sprintf("  ca_file: %q\n", r.CoordinatorCACert))
			b.WriteString(fmt.Sprintf("  cert_file: %q\n", r.CoordinatorCertFile))
			b.WriteString(fmt.Sprintf("  key_file: %q\n", r.CoordinatorKeyFile))
		} else if !isProd {
			b.WriteString("  allow_insecure: true\n")
		}
	}
	b.WriteString("\n")

	// Circuit breakers
	if r.EnableCircuitBreaker {
		b.WriteString("circuit_breakers:\n")
		b.WriteString("  standard:\n")
		b.WriteString("    max_requests: 5\n")
		b.WriteString("    interval: \"60s\"\n")
		b.WriteString(fmt.Sprintf("    timeout: %q\n", r.CBTimeout))
		b.WriteString(fmt.Sprintf("    failure_threshold: %s\n", r.CBFailureThreshold))
		b.WriteString("\n")
	}

	// Paths
	b.WriteString("paths:\n")
	for i, route := range r.Routes {
		b.WriteString(fmt.Sprintf("  %s:\n", route.Path))
		b.WriteString(fmt.Sprintf("    %s:\n", route.Method))
		b.WriteString("      x-csar-backend:\n")
		b.WriteString(fmt.Sprintf("        target_url: %q\n", route.TargetURL))

		// JWT
		if r.EnableJWT && r.JWKSURL != "" {
			b.WriteString("      x-csar-authn-validate:\n")
			b.WriteString(fmt.Sprintf("        jwks_url: %q\n", r.JWKSURL))
			b.WriteString("        # issuer: \"https://auth.example.com/\"\n")
			b.WriteString("        # audiences:\n")
			b.WriteString("        #   - \"my-api\"\n")
		}

		// Route security — reference profile or inline
		if i < len(r.RouteSecurities) && r.RouteSecurities[i].IsSecured {
			sec := r.RouteSecurities[i]
			profileName := securityProfileName(sec)
			if profileName != "" {
				b.WriteString(fmt.Sprintf("      x-csar-security: %q\n", profileName))
			} else {
				b.WriteString("      x-csar-security:\n")
				if sec.KMSKeyID != "" {
					b.WriteString(fmt.Sprintf("        kms_key_id: %q\n", sec.KMSKeyID))
				}
				b.WriteString(fmt.Sprintf("        token_ref: %q\n", sec.TokenRef))
				b.WriteString(fmt.Sprintf("        inject_header: %q\n", sec.InjectHeader))
				b.WriteString(fmt.Sprintf("        inject_format: %q\n", sec.InjectFormat))
			}
		} else if i >= len(r.RouteSecurities) {
			// Legacy fallback: show commented-out security placeholder
			b.WriteString("      # x-csar-security:\n")
			b.WriteString("      #   kms_key_id: \"your-key-id\"\n")
			b.WriteString("      #   token_ref: \"api_token\"\n")
			b.WriteString("      #   inject_header: \"Authorization\"\n")
			b.WriteString("      #   inject_format: \"Bearer {token}\"\n")
		}

		// Traffic
		b.WriteString("      x-csar-traffic:\n")
		b.WriteString(fmt.Sprintf("        rps: %s\n", floatOrDefault(route.RPS, "10.0")))
		b.WriteString(fmt.Sprintf("        burst: %s\n", intOrDefault(route.Burst, "20")))
		b.WriteString(fmt.Sprintf("        max_wait: %q\n", route.MaxWait))
		if r.RateLimitBackend != "local" && r.RateLimitBackend != "" {
			b.WriteString(fmt.Sprintf("        backend: %q\n", r.RateLimitBackend))
		}

		// Resilience
		if r.EnableCircuitBreaker {
			b.WriteString("      x-csar-resilience:\n")
			b.WriteString("        circuit_breaker: \"standard\"\n")
		}

		// Retry
		if r.EnableRetry {
			b.WriteString("      x-csar-retry:\n")
			b.WriteString(fmt.Sprintf("        max_attempts: %s\n", intOrDefault(r.RetryAttempts, "3")))
			b.WriteString("        backoff: \"1s\"\n")
			b.WriteString("        max_backoff: \"10s\"\n")
		}
	}

	// Health endpoint
	b.WriteString("\n  /health:\n")
	b.WriteString("    get:\n")
	b.WriteString("      x-csar-backend:\n")
	b.WriteString("        target_url: \"http://localhost:8080\"\n")

	return b.String()
}

// collectSecurityProfiles gathers unique security profiles from all routes
// to emit as reusable security_profiles in config.yaml.
func collectSecurityProfiles(r *GenerateResult) map[string]RouteSecurityAnswers {
	profiles := make(map[string]RouteSecurityAnswers)
	for _, sec := range r.RouteSecurities {
		if !sec.IsSecured || sec.TokenRef == "" {
			continue
		}
		name := securityProfileName(sec)
		if name != "" {
			profiles[name] = sec
		}
	}
	return profiles
}

// securityProfileName generates a profile name from security answers.
// Returns empty string if not enough info for a profile.
func securityProfileName(sec RouteSecurityAnswers) string {
	if sec.TokenRef == "" {
		return ""
	}
	return sec.TokenRef
}
