// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/csar/v1/auth.proto

package csarv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TokenRequest identifies which encrypted token to fetch.
type TokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token_ref is the logical reference name (e.g. "my_api_token", "orders_token").
	TokenRef      string `protobuf:"bytes,1,opt,name=token_ref,json=tokenRef,proto3" json:"token_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRequest) Reset() {
	*x = TokenRequest{}
	mi := &file_proto_csar_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRequest) ProtoMessage() {}

func (x *TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_csar_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRequest.ProtoReflect.Descriptor instead.
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_csar_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *TokenRequest) GetTokenRef() string {
	if x != nil {
		return x.TokenRef
	}
	return ""
}

// TokenResponse contains the encrypted token blob and metadata.
type TokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token_ref echoes back the requested reference.
	TokenRef string `protobuf:"bytes,1,opt,name=token_ref,json=tokenRef,proto3" json:"token_ref,omitempty"`
	// encrypted_token is the encrypted blob (envelope-encrypted via KMS).
	EncryptedToken []byte `protobuf:"bytes,2,opt,name=encrypted_token,json=encryptedToken,proto3" json:"encrypted_token,omitempty"`
	// kms_key_id is the KMS key that was used to encrypt this token.
	KmsKeyId string `protobuf:"bytes,3,opt,name=kms_key_id,json=kmsKeyId,proto3" json:"kms_key_id,omitempty"`
	// version is an opaque version string for cache invalidation.
	Version       string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_proto_csar_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_csar_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_csar_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *TokenResponse) GetTokenRef() string {
	if x != nil {
		return x.TokenRef
	}
	return ""
}

func (x *TokenResponse) GetEncryptedToken() []byte {
	if x != nil {
		return x.EncryptedToken
	}
	return nil
}

func (x *TokenResponse) GetKmsKeyId() string {
	if x != nil {
		return x.KmsKeyId
	}
	return ""
}

func (x *TokenResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// ListTokenRefsRequest requests available token references.
type ListTokenRefsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokenRefsRequest) Reset() {
	*x = ListTokenRefsRequest{}
	mi := &file_proto_csar_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokenRefsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokenRefsRequest) ProtoMessage() {}

func (x *ListTokenRefsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_csar_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokenRefsRequest.ProtoReflect.Descriptor instead.
func (*ListTokenRefsRequest) Descriptor() ([]byte, []int) {
	return file_proto_csar_v1_auth_proto_rawDescGZIP(), []int{2}
}

// ListTokenRefsResponse contains all available token references.
type ListTokenRefsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refs          []*TokenRefInfo        `protobuf:"bytes,1,rep,name=refs,proto3" json:"refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokenRefsResponse) Reset() {
	*x = ListTokenRefsResponse{}
	mi := &file_proto_csar_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokenRefsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokenRefsResponse) ProtoMessage() {}

func (x *ListTokenRefsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_csar_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokenRefsResponse.ProtoReflect.Descriptor instead.
func (*ListTokenRefsResponse) Descriptor() ([]byte, []int) {
	return file_proto_csar_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *ListTokenRefsResponse) GetRefs() []*TokenRefInfo {
	if x != nil {
		return x.Refs
	}
	return nil
}

// TokenRefInfo describes a single token reference.
type TokenRefInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token_ref is the logical reference name.
	TokenRef string `protobuf:"bytes,1,opt,name=token_ref,json=tokenRef,proto3" json:"token_ref,omitempty"`
	// kms_key_id is the KMS key associated with this token.
	KmsKeyId string `protobuf:"bytes,2,opt,name=kms_key_id,json=kmsKeyId,proto3" json:"kms_key_id,omitempty"`
	// description is a human-readable description.
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRefInfo) Reset() {
	*x = TokenRefInfo{}
	mi := &file_proto_csar_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRefInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRefInfo) ProtoMessage() {}

func (x *TokenRefInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_csar_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRefInfo.ProtoReflect.Descriptor instead.
func (*TokenRefInfo) Descriptor() ([]byte, []int) {
	return file_proto_csar_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *TokenRefInfo) GetTokenRef() string {
	if x != nil {
		return x.TokenRef
	}
	return ""
}

func (x *TokenRefInfo) GetKmsKeyId() string {
	if x != nil {
		return x.KmsKeyId
	}
	return ""
}

func (x *TokenRefInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_proto_csar_v1_auth_proto protoreflect.FileDescriptor

const file_proto_csar_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x18proto/csar/v1/auth.proto\x12\acsar.v1\"+\n" +
	"\fTokenRequest\x12\x1b\n" +
	"\ttoken_ref\x18\x01 \x01(\tR\btokenRef\"\x8d\x01\n" +
	"\rTokenResponse\x12\x1b\n" +
	"\ttoken_ref\x18\x01 \x01(\tR\btokenRef\x12'\n" +
	"\x0fencrypted_token\x18\x02 \x01(\fR\x0eencryptedToken\x12\x1c\n" +
	"\n" +
	"kms_key_id\x18\x03 \x01(\tR\bkmsKeyId\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"\x16\n" +
	"\x14ListTokenRefsRequest\"B\n" +
	"\x15ListTokenRefsResponse\x12)\n" +
	"\x04refs\x18\x01 \x03(\v2\x15.csar.v1.TokenRefInfoR\x04refs\"k\n" +
	"\fTokenRefInfo\x12\x1b\n" +
	"\ttoken_ref\x18\x01 \x01(\tR\btokenRef\x12\x1c\n" +
	"\n" +
	"kms_key_id\x18\x02 \x01(\tR\bkmsKeyId\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription2\xa1\x01\n" +
	"\vAuthService\x12B\n" +
	"\x11GetEncryptedToken\x12\x15.csar.v1.TokenRequest\x1a\x16.csar.v1.TokenResponse\x12N\n" +
	"\rListTokenRefs\x12\x1d.csar.v1.ListTokenRefsRequest\x1a\x1e.csar.v1.ListTokenRefsResponseB-Z+github.com/ledatu/csar/proto/csar/v1;csarv1b\x06proto3"

var (
	file_proto_csar_v1_auth_proto_rawDescOnce sync.Once
	file_proto_csar_v1_auth_proto_rawDescData []byte
)

func file_proto_csar_v1_auth_proto_rawDescGZIP() []byte {
	file_proto_csar_v1_auth_proto_rawDescOnce.Do(func() {
		file_proto_csar_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_csar_v1_auth_proto_rawDesc), len(file_proto_csar_v1_auth_proto_rawDesc)))
	})
	return file_proto_csar_v1_auth_proto_rawDescData
}

var file_proto_csar_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_csar_v1_auth_proto_goTypes = []any{
	(*TokenRequest)(nil),          // 0: csar.v1.TokenRequest
	(*TokenResponse)(nil),         // 1: csar.v1.TokenResponse
	(*ListTokenRefsRequest)(nil),  // 2: csar.v1.ListTokenRefsRequest
	(*ListTokenRefsResponse)(nil), // 3: csar.v1.ListTokenRefsResponse
	(*TokenRefInfo)(nil),          // 4: csar.v1.TokenRefInfo
}
var file_proto_csar_v1_auth_proto_depIdxs = []int32{
	4, // 0: csar.v1.ListTokenRefsResponse.refs:type_name -> csar.v1.TokenRefInfo
	0, // 1: csar.v1.AuthService.GetEncryptedToken:input_type -> csar.v1.TokenRequest
	2, // 2: csar.v1.AuthService.ListTokenRefs:input_type -> csar.v1.ListTokenRefsRequest
	1, // 3: csar.v1.AuthService.GetEncryptedToken:output_type -> csar.v1.TokenResponse
	3, // 4: csar.v1.AuthService.ListTokenRefs:output_type -> csar.v1.ListTokenRefsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_csar_v1_auth_proto_init() }
func file_proto_csar_v1_auth_proto_init() {
	if File_proto_csar_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_csar_v1_auth_proto_rawDesc), len(file_proto_csar_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_csar_v1_auth_proto_goTypes,
		DependencyIndexes: file_proto_csar_v1_auth_proto_depIdxs,
		MessageInfos:      file_proto_csar_v1_auth_proto_msgTypes,
	}.Build()
	File_proto_csar_v1_auth_proto = out.File
	file_proto_csar_v1_auth_proto_goTypes = nil
	file_proto_csar_v1_auth_proto_depIdxs = nil
}
