// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/csar/v1/coordinator.proto

package csarv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SubscribeRequest is sent by a Router when connecting to the Coordinator.
type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// router_id is the unique identifier of the connecting router.
	RouterId string `protobuf:"bytes,1,opt,name=router_id,json=routerId,proto3" json:"router_id,omitempty"`
	// router_address is the router's network address for peer discovery.
	RouterAddress string `protobuf:"bytes,2,opt,name=router_address,json=routerAddress,proto3" json:"router_address,omitempty"`
	// metadata contains arbitrary key-value pairs (e.g. version, region).
	Metadata map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// last_seen_version is the watermark of the last ConfigUpdate version
	// processed by this router. On reconnect, the coordinator replays any
	// token invalidation events with version > last_seen_version.
	// Zero means the router has no prior state (fresh start).
	LastSeenVersion uint64 `protobuf:"varint,4,opt,name=last_seen_version,json=lastSeenVersion,proto3" json:"last_seen_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_csar_v1_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_csar_v1_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_csar_v1_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetRouterId() string {
	if x != nil {
		return x.RouterId
	}
	return ""
}

func (x *SubscribeRequest) GetRouterAddress() string {
	if x != nil {
		return x.RouterAddress
	}
	return ""
}

func (x *SubscribeRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SubscribeRequest) GetLastSeenVersion() uint64 {
	if x != nil {
		return x.LastSeenVersion
	}
	return 0
}

// ConfigUpdate is a streamed message from Coordinator to Router.
// It uses a oneof to carry different types of updates.
type ConfigUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// version is a monotonically increasing config version for ordering.
	Version uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Types that are valid to be assigned to Update:
	//
	//	*ConfigUpdate_RouteSnapshot
	//	*ConfigUpdate_QuotaAssignment
	//	*ConfigUpdate_TokenInvalidation
	Update        isConfigUpdate_Update `protobuf_oneof:"update"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	mi := &file_proto_csar_v1_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_csar_v1_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_proto_csar_v1_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigUpdate) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConfigUpdate) GetUpdate() isConfigUpdate_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *ConfigUpdate) GetRouteSnapshot() *RouteSnapshot {
	if x != nil {
		if x, ok := x.Update.(*ConfigUpdate_RouteSnapshot); ok {
			return x.RouteSnapshot
		}
	}
	return nil
}

func (x *ConfigUpdate) GetQuotaAssignment() *QuotaAssignment {
	if x != nil {
		if x, ok := x.Update.(*ConfigUpdate_QuotaAssignment); ok {
			return x.QuotaAssignment
		}
	}
	return nil
}

func (x *ConfigUpdate) GetTokenInvalidation() *TokenInvalidation {
	if x != nil {
		if x, ok := x.Update.(*ConfigUpdate_TokenInvalidation); ok {
			return x.TokenInvalidation
		}
	}
	return nil
}

type isConfigUpdate_Update interface {
	isConfigUpdate_Update()
}

type ConfigUpdate_RouteSnapshot struct {
	// Full route configuration snapshot.
	RouteSnapshot *RouteSnapshot `protobuf:"bytes,2,opt,name=route_snapshot,json=routeSnapshot,proto3,oneof"`
}

type ConfigUpdate_QuotaAssignment struct {
	// Quota assignment for this specific router.
	QuotaAssignment *QuotaAssignment `protobuf:"bytes,4,opt,name=quota_assignment,json=quotaAssignment,proto3,oneof"`
}

type ConfigUpdate_TokenInvalidation struct {
	// Token invalidation event — instructs the router to clear
	// stale-cached tokens after a rotation (audit §1.2).
	TokenInvalidation *TokenInvalidation `protobuf:"bytes,5,opt,name=token_invalidation,json=tokenInvalidation,proto3,oneof"`
}

func (*ConfigUpdate_RouteSnapshot) isConfigUpdate_Update() {}

func (*ConfigUpdate_QuotaAssignment) isConfigUpdate_Update() {}

func (*ConfigUpdate_TokenInvalidation) isConfigUpdate_Update() {}

// TokenInvalidation tells routers to clear stale-cached tokens.
// Pushed by the Coordinator when tokens are rotated in etcd (audit §1.2).
type TokenInvalidation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token_refs lists the token reference names to invalidate.
	// If empty, all tokens should be invalidated.
	TokenRefs []string `protobuf:"bytes,1,rep,name=token_refs,json=tokenRefs,proto3" json:"token_refs,omitempty"`
	// invalidation_version is a monotonic version for this invalidation event.
	// Routers track this to detect missed invalidations on reconnect.
	InvalidationVersion uint64 `protobuf:"varint,2,opt,name=invalidation_version,json=invalidationVersion,proto3" json:"invalidation_version,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TokenInvalidation) Reset() {
	*x = TokenInvalidation{}
	mi := &file_proto_csar_v1_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenInvalidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenInvalidation) ProtoMessage() {}

func (x *TokenInvalidation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_csar_v1_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenInvalidation.ProtoReflect.Descriptor instead.
func (*TokenInvalidation) Descriptor() ([]byte, []int) {
	return file_proto_csar_v1_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *TokenInvalidation) GetTokenRefs() []string {
	if x != nil {
		return x.TokenRefs
	}
	return nil
}

func (x *TokenInvalidation) GetInvalidationVersion() uint64 {
	if x != nil {
		return x.InvalidationVersion
	}
	return 0
}

// RouteSnapshot contains the full set of routes.
type RouteSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*RouteConfig         `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteSnapshot) Reset() {
	*x = RouteSnapshot{}
	mi := &file_proto_csar_v1_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteSnapshot) ProtoMessage() {}

func (x *RouteSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_csar_v1_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteSnapshot.ProtoReflect.Descriptor instead.
func (*RouteSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_csar_v1_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *RouteSnapshot) GetRoutes() []*RouteConfig {
	if x != nil {
		return x.Routes
	}
	return nil
}

// RouteConfig describes a single route pushed to the router.
type RouteConfig struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RouteId   string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	Path      string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Method    string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	TargetUrl string                 `protobuf:"bytes,4,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	// Security settings (optional).
	Security *SecurityConfig `protobuf:"bytes,5,opt,name=security,proto3" json:"security,omitempty"`
	// Traffic settings (optional).
	Traffic *TrafficConfig `protobuf:"bytes,6,opt,name=traffic,proto3" json:"traffic,omitempty"`
	// Resilience profile name (optional).
	ResilienceProfile string `protobuf:"bytes,7,opt,name=resilience_profile,json=resilienceProfile,proto3" json:"resilience_profile,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RouteConfig) Reset() {
	*x = RouteConfig{}
	mi := &file_proto_csar_v1_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteConfig) ProtoMessage() {}

func (x *RouteConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_csar_v1_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteConfig.ProtoReflect.Descriptor instead.
func (*RouteConfig) Descriptor() ([]byte, []int) {
	return file_proto_csar_v1_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *RouteConfig) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *RouteConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RouteConfig) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RouteConfig) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *RouteConfig) GetSecurity() *SecurityConfig {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *RouteConfig) GetTraffic() *TrafficConfig {
	if x != nil {
		return x.Traffic
	}
	return nil
}

func (x *RouteConfig) GetResilienceProfile() string {
	if x != nil {
		return x.ResilienceProfile
	}
	return ""
}

// SecurityConfig pushed to routers — contains the header injection config.
// Routers obtain decrypted tokens via AuthService.GetEncryptedToken + KMS decryption.
type SecurityConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenRef      string                 `protobuf:"bytes,1,opt,name=token_ref,json=tokenRef,proto3" json:"token_ref,omitempty"`
	InjectHeader  string                 `protobuf:"bytes,2,opt,name=inject_header,json=injectHeader,proto3" json:"inject_header,omitempty"`
	InjectFormat  string                 `protobuf:"bytes,3,opt,name=inject_format,json=injectFormat,proto3" json:"inject_format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityConfig) Reset() {
	*x = SecurityConfig{}
	mi := &file_proto_csar_v1_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityConfig) ProtoMessage() {}

func (x *SecurityConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_csar_v1_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityConfig.ProtoReflect.Descriptor instead.
func (*SecurityConfig) Descriptor() ([]byte, []int) {
	return file_proto_csar_v1_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *SecurityConfig) GetTokenRef() string {
	if x != nil {
		return x.TokenRef
	}
	return ""
}

func (x *SecurityConfig) GetInjectHeader() string {
	if x != nil {
		return x.InjectHeader
	}
	return ""
}

func (x *SecurityConfig) GetInjectFormat() string {
	if x != nil {
		return x.InjectFormat
	}
	return ""
}

// TrafficConfig describes rate limiting parameters.
type TrafficConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rps           float64                `protobuf:"fixed64,1,opt,name=rps,proto3" json:"rps,omitempty"`
	Burst         int32                  `protobuf:"varint,2,opt,name=burst,proto3" json:"burst,omitempty"`
	MaxWait       *durationpb.Duration   `protobuf:"bytes,3,opt,name=max_wait,json=maxWait,proto3" json:"max_wait,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficConfig) Reset() {
	*x = TrafficConfig{}
	mi := &file_proto_csar_v1_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficConfig) ProtoMessage() {}

func (x *TrafficConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_csar_v1_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficConfig.ProtoReflect.Descriptor instead.
func (*TrafficConfig) Descriptor() ([]byte, []int) {
	return file_proto_csar_v1_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *TrafficConfig) GetRps() float64 {
	if x != nil {
		return x.Rps
	}
	return 0
}

func (x *TrafficConfig) GetBurst() int32 {
	if x != nil {
		return x.Burst
	}
	return 0
}

func (x *TrafficConfig) GetMaxWait() *durationpb.Duration {
	if x != nil {
		return x.MaxWait
	}
	return nil
}

// QuotaAssignment tells a router its allocated share of the global rate limits.
type QuotaAssignment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of route_id -> assigned quota for this router.
	Quotas        map[string]*RouteQuota `protobuf:"bytes,1,rep,name=quotas,proto3" json:"quotas,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuotaAssignment) Reset() {
	*x = QuotaAssignment{}
	mi := &file_proto_csar_v1_coordinator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaAssignment) ProtoMessage() {}

func (x *QuotaAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_csar_v1_coordinator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaAssignment.ProtoReflect.Descriptor instead.
func (*QuotaAssignment) Descriptor() ([]byte, []int) {
	return file_proto_csar_v1_coordinator_proto_rawDescGZIP(), []int{7}
}

func (x *QuotaAssignment) GetQuotas() map[string]*RouteQuota {
	if x != nil {
		return x.Quotas
	}
	return nil
}

// RouteQuota is the per-router rate limit allocation for a single route.
type RouteQuota struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rps           float64                `protobuf:"fixed64,1,opt,name=rps,proto3" json:"rps,omitempty"`
	Burst         int32                  `protobuf:"varint,2,opt,name=burst,proto3" json:"burst,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteQuota) Reset() {
	*x = RouteQuota{}
	mi := &file_proto_csar_v1_coordinator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteQuota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteQuota) ProtoMessage() {}

func (x *RouteQuota) ProtoReflect() protoreflect.Message {
	mi := &file_proto_csar_v1_coordinator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteQuota.ProtoReflect.Descriptor instead.
func (*RouteQuota) Descriptor() ([]byte, []int) {
	return file_proto_csar_v1_coordinator_proto_rawDescGZIP(), []int{8}
}

func (x *RouteQuota) GetRps() float64 {
	if x != nil {
		return x.Rps
	}
	return 0
}

func (x *RouteQuota) GetBurst() int32 {
	if x != nil {
		return x.Burst
	}
	return 0
}

// HealthReport is sent by a router to the coordinator.
type HealthReport struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	RouterId string                 `protobuf:"bytes,1,opt,name=router_id,json=routerId,proto3" json:"router_id,omitempty"`
	Healthy  bool                   `protobuf:"varint,2,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// Current queue depths per route.
	QueueDepths map[string]int64 `protobuf:"bytes,3,rep,name=queue_depths,json=queueDepths,proto3" json:"queue_depths,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Metadata (uptime, version, etc.).
	Metadata      map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthReport) Reset() {
	*x = HealthReport{}
	mi := &file_proto_csar_v1_coordinator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReport) ProtoMessage() {}

func (x *HealthReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_csar_v1_coordinator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReport.ProtoReflect.Descriptor instead.
func (*HealthReport) Descriptor() ([]byte, []int) {
	return file_proto_csar_v1_coordinator_proto_rawDescGZIP(), []int{9}
}

func (x *HealthReport) GetRouterId() string {
	if x != nil {
		return x.RouterId
	}
	return ""
}

func (x *HealthReport) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthReport) GetQueueDepths() map[string]int64 {
	if x != nil {
		return x.QueueDepths
	}
	return nil
}

func (x *HealthReport) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// HealthAck is the coordinator's response to a health report.
type HealthAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthAck) Reset() {
	*x = HealthAck{}
	mi := &file_proto_csar_v1_coordinator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthAck) ProtoMessage() {}

func (x *HealthAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_csar_v1_coordinator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthAck.ProtoReflect.Descriptor instead.
func (*HealthAck) Descriptor() ([]byte, []int) {
	return file_proto_csar_v1_coordinator_proto_rawDescGZIP(), []int{10}
}

func (x *HealthAck) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

var File_proto_csar_v1_coordinator_proto protoreflect.FileDescriptor

const file_proto_csar_v1_coordinator_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/csar/v1/coordinator.proto\x12\acsar.v1\x1a\x1egoogle/protobuf/duration.proto\"\x84\x02\n" +
	"\x10SubscribeRequest\x12\x1b\n" +
	"\trouter_id\x18\x01 \x01(\tR\brouterId\x12%\n" +
	"\x0erouter_address\x18\x02 \x01(\tR\rrouterAddress\x12C\n" +
	"\bmetadata\x18\x03 \x03(\v2'.csar.v1.SubscribeRequest.MetadataEntryR\bmetadata\x12*\n" +
	"\x11last_seen_version\x18\x04 \x01(\x04R\x0flastSeenVersion\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa2\x02\n" +
	"\fConfigUpdate\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12?\n" +
	"\x0eroute_snapshot\x18\x02 \x01(\v2\x16.csar.v1.RouteSnapshotH\x00R\rrouteSnapshot\x12E\n" +
	"\x10quota_assignment\x18\x04 \x01(\v2\x18.csar.v1.QuotaAssignmentH\x00R\x0fquotaAssignment\x12K\n" +
	"\x12token_invalidation\x18\x05 \x01(\v2\x1a.csar.v1.TokenInvalidationH\x00R\x11tokenInvalidationB\b\n" +
	"\x06updateJ\x04\b\x03\x10\x04R\x13secret_distribution\"e\n" +
	"\x11TokenInvalidation\x12\x1d\n" +
	"\n" +
	"token_refs\x18\x01 \x03(\tR\ttokenRefs\x121\n" +
	"\x14invalidation_version\x18\x02 \x01(\x04R\x13invalidationVersion\"=\n" +
	"\rRouteSnapshot\x12,\n" +
	"\x06routes\x18\x01 \x03(\v2\x14.csar.v1.RouteConfigR\x06routes\"\x89\x02\n" +
	"\vRouteConfig\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x1d\n" +
	"\n" +
	"target_url\x18\x04 \x01(\tR\ttargetUrl\x123\n" +
	"\bsecurity\x18\x05 \x01(\v2\x17.csar.v1.SecurityConfigR\bsecurity\x120\n" +
	"\atraffic\x18\x06 \x01(\v2\x16.csar.v1.TrafficConfigR\atraffic\x12-\n" +
	"\x12resilience_profile\x18\a \x01(\tR\x11resilienceProfile\"w\n" +
	"\x0eSecurityConfig\x12\x1b\n" +
	"\ttoken_ref\x18\x01 \x01(\tR\btokenRef\x12#\n" +
	"\rinject_header\x18\x02 \x01(\tR\finjectHeader\x12#\n" +
	"\rinject_format\x18\x03 \x01(\tR\finjectFormat\"m\n" +
	"\rTrafficConfig\x12\x10\n" +
	"\x03rps\x18\x01 \x01(\x01R\x03rps\x12\x14\n" +
	"\x05burst\x18\x02 \x01(\x05R\x05burst\x124\n" +
	"\bmax_wait\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\amaxWait\"\x9f\x01\n" +
	"\x0fQuotaAssignment\x12<\n" +
	"\x06quotas\x18\x01 \x03(\v2$.csar.v1.QuotaAssignment.QuotasEntryR\x06quotas\x1aN\n" +
	"\vQuotasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.csar.v1.RouteQuotaR\x05value:\x028\x01\"4\n" +
	"\n" +
	"RouteQuota\x12\x10\n" +
	"\x03rps\x18\x01 \x01(\x01R\x03rps\x12\x14\n" +
	"\x05burst\x18\x02 \x01(\x05R\x05burst\"\xce\x02\n" +
	"\fHealthReport\x12\x1b\n" +
	"\trouter_id\x18\x01 \x01(\tR\brouterId\x12\x18\n" +
	"\ahealthy\x18\x02 \x01(\bR\ahealthy\x12I\n" +
	"\fqueue_depths\x18\x03 \x03(\v2&.csar.v1.HealthReport.QueueDepthsEntryR\vqueueDepths\x12?\n" +
	"\bmetadata\x18\x04 \x03(\v2#.csar.v1.HealthReport.MetadataEntryR\bmetadata\x1a>\n" +
	"\x10QueueDepthsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"/\n" +
	"\tHealthAck\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged2\x90\x01\n" +
	"\x12CoordinatorService\x12?\n" +
	"\tSubscribe\x12\x19.csar.v1.SubscribeRequest\x1a\x15.csar.v1.ConfigUpdate0\x01\x129\n" +
	"\fReportHealth\x12\x15.csar.v1.HealthReport\x1a\x12.csar.v1.HealthAckB-Z+github.com/ledatu/csar/proto/csar/v1;csarv1b\x06proto3"

var (
	file_proto_csar_v1_coordinator_proto_rawDescOnce sync.Once
	file_proto_csar_v1_coordinator_proto_rawDescData []byte
)

func file_proto_csar_v1_coordinator_proto_rawDescGZIP() []byte {
	file_proto_csar_v1_coordinator_proto_rawDescOnce.Do(func() {
		file_proto_csar_v1_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_csar_v1_coordinator_proto_rawDesc), len(file_proto_csar_v1_coordinator_proto_rawDesc)))
	})
	return file_proto_csar_v1_coordinator_proto_rawDescData
}

var file_proto_csar_v1_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_csar_v1_coordinator_proto_goTypes = []any{
	(*SubscribeRequest)(nil),    // 0: csar.v1.SubscribeRequest
	(*ConfigUpdate)(nil),        // 1: csar.v1.ConfigUpdate
	(*TokenInvalidation)(nil),   // 2: csar.v1.TokenInvalidation
	(*RouteSnapshot)(nil),       // 3: csar.v1.RouteSnapshot
	(*RouteConfig)(nil),         // 4: csar.v1.RouteConfig
	(*SecurityConfig)(nil),      // 5: csar.v1.SecurityConfig
	(*TrafficConfig)(nil),       // 6: csar.v1.TrafficConfig
	(*QuotaAssignment)(nil),     // 7: csar.v1.QuotaAssignment
	(*RouteQuota)(nil),          // 8: csar.v1.RouteQuota
	(*HealthReport)(nil),        // 9: csar.v1.HealthReport
	(*HealthAck)(nil),           // 10: csar.v1.HealthAck
	nil,                         // 11: csar.v1.SubscribeRequest.MetadataEntry
	nil,                         // 12: csar.v1.QuotaAssignment.QuotasEntry
	nil,                         // 13: csar.v1.HealthReport.QueueDepthsEntry
	nil,                         // 14: csar.v1.HealthReport.MetadataEntry
	(*durationpb.Duration)(nil), // 15: google.protobuf.Duration
}
var file_proto_csar_v1_coordinator_proto_depIdxs = []int32{
	11, // 0: csar.v1.SubscribeRequest.metadata:type_name -> csar.v1.SubscribeRequest.MetadataEntry
	3,  // 1: csar.v1.ConfigUpdate.route_snapshot:type_name -> csar.v1.RouteSnapshot
	7,  // 2: csar.v1.ConfigUpdate.quota_assignment:type_name -> csar.v1.QuotaAssignment
	2,  // 3: csar.v1.ConfigUpdate.token_invalidation:type_name -> csar.v1.TokenInvalidation
	4,  // 4: csar.v1.RouteSnapshot.routes:type_name -> csar.v1.RouteConfig
	5,  // 5: csar.v1.RouteConfig.security:type_name -> csar.v1.SecurityConfig
	6,  // 6: csar.v1.RouteConfig.traffic:type_name -> csar.v1.TrafficConfig
	15, // 7: csar.v1.TrafficConfig.max_wait:type_name -> google.protobuf.Duration
	12, // 8: csar.v1.QuotaAssignment.quotas:type_name -> csar.v1.QuotaAssignment.QuotasEntry
	13, // 9: csar.v1.HealthReport.queue_depths:type_name -> csar.v1.HealthReport.QueueDepthsEntry
	14, // 10: csar.v1.HealthReport.metadata:type_name -> csar.v1.HealthReport.MetadataEntry
	8,  // 11: csar.v1.QuotaAssignment.QuotasEntry.value:type_name -> csar.v1.RouteQuota
	0,  // 12: csar.v1.CoordinatorService.Subscribe:input_type -> csar.v1.SubscribeRequest
	9,  // 13: csar.v1.CoordinatorService.ReportHealth:input_type -> csar.v1.HealthReport
	1,  // 14: csar.v1.CoordinatorService.Subscribe:output_type -> csar.v1.ConfigUpdate
	10, // 15: csar.v1.CoordinatorService.ReportHealth:output_type -> csar.v1.HealthAck
	14, // [14:16] is the sub-list for method output_type
	12, // [12:14] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_csar_v1_coordinator_proto_init() }
func file_proto_csar_v1_coordinator_proto_init() {
	if File_proto_csar_v1_coordinator_proto != nil {
		return
	}
	file_proto_csar_v1_coordinator_proto_msgTypes[1].OneofWrappers = []any{
		(*ConfigUpdate_RouteSnapshot)(nil),
		(*ConfigUpdate_QuotaAssignment)(nil),
		(*ConfigUpdate_TokenInvalidation)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_csar_v1_coordinator_proto_rawDesc), len(file_proto_csar_v1_coordinator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_csar_v1_coordinator_proto_goTypes,
		DependencyIndexes: file_proto_csar_v1_coordinator_proto_depIdxs,
		MessageInfos:      file_proto_csar_v1_coordinator_proto_msgTypes,
	}.Build()
	File_proto_csar_v1_coordinator_proto = out.File
	file_proto_csar_v1_coordinator_proto_goTypes = nil
	file_proto_csar_v1_coordinator_proto_depIdxs = nil
}
